### PR TITLE
Enable detection for debug option

### PR DESCRIPTION
**Pull request by KeweiCodes**
Not sure why this was commented in the first place?

### CODE REVIEW

**Comment by KeweiCodes** [comment]
https://github.com/andreassolberg/jso/issues/11

**Comment by KeweiCodes** [comment]
https://github.com/andreassolberg/jso/issues/11 ?

**Comment by andrroy** [comment]
@KeweiCodes In order to disable debug logging everywhere, I think you have to enable detection for debug mode in [utils.js:94](https://github.com/andreassolberg/jso/blob/f2e710a9696eb40c3df4ab24d94c710b5c649345/src/utils.js#L94) as well. Would you mind added that to your PR? 🙂

**Comment by andreassolberg** [comment]
Thank you so much for your PR. This issue is now fixed in version >=4.0.1

**Pull request closed without merging**
